### ISSUE TITLE
squeezebox-oe1 @ Logitech Media Server 7.7.5 / 7.8 / 7.9 @ Debian 8.1

### ISSUE THREAD

**Issue by moritzwie** [tischlda/squeezebox-oe1#1]
Hey there,

Im a big fan of RadioOe1 and was very happy the time I found your Plugin for the Squeezebox-System.

Unfortunatly its not working anymore on my setup (Logitech Media Server 7.7.5 / 7.8 / 7.9 @ Debian 8.1).

I get it installed. When I want to play RadioOe1 on any of my devices (Squeezebox Boom / Android SqueezePlayer) the devices get all the info from the server but end up displaying: 

ERROR: NO ITEMS FOUND IN PLAYLIST

Today i tried this one  Logitech Media Server 7.7.5 / 7.8 / 7.9.
The LMS packages are coming from here:
http://downloads.slimdevices.com/nightly/?ver=7.8
http://downloads.slimdevices.com/nightly/?ver=7.9

It was working on Debian 8 and LMS 7.8 though (my last setup).

Is there any way you could provide some support?

Thank you so much for this plugin, its my main music source for the squeezebox.

Enjoy _ moritz

**Comment by tischlda** [comment]
Hi!

Sorry to hear about that problem. Unfortunately I won't be able to look into it for the next two weeks, but after that I'll try to reproduce it and come back to you.

-- David

**Comment by moritzwie** [comment]
Hey David,

thanks for your quick response. Actually I thought about compensating you a little for your work. Even before without having the issue.

## Is there any way to support you?

M. Wiederaenders

**Comment by moritzwie** [comment]
Hola David,

I just want to let you know that everything works fine now.
I cant recreate the situation as in the meantime there have been quite a few changes on my machines.

Thank you for your efforts!
